<?xml version="1.0" encoding="UTF-8"?>
<!-- Dado el siguiente documento XML, escribir el contenido del archivo fichas.xsd que permita validarlo:-->
<!DOCTYPE productos [
   <!ELEMENT productos (producto)*>
   <!ELEMENT producto (nombre, identificacion)>
   <!ELEMENT identificacion (#PCDATA | codigo | id)*>
   <!ELEMENT codigo (#PCDATA)>
   <!ELEMENT id (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
]>
<productos>
   <producto>
    <nombre>martillo</nombre>
    <identificacion>
       Quedan 14 unidades.
       <codigo>MAR264</codigo>
    </identificacion>
   </producto>
   <producto>
       <nombre>destornillador</nombre>
        <identificacion>
        No hay stock.
        <codigo>DES387</codigo>
        <id>678984</id>
        </identificacion>
   </producto>
</productos>
